apiVersion: v1
kind: Secret
metadata:
  name: ss-secrets
  namespace: sanos-salvos
type: Opaque
stringData:
  # PostgreSQL
  POSTGRES_DB: sanosysalvos
  POSTGRES_USER: ssuser
  POSTGRES_PASSWORD: ss_dev_pass_2024
  POSTGRES_URL_JDBC: jdbc:postgresql://postgres:5432/sanosysalvos
  POSTGRES_URL_PY: postgresql://ssuser:ss_dev_pass_2024@postgres:5432/sanosysalvos

  # MongoDB
  MONGO_ROOT_USER: mongoroot
  MONGO_ROOT_PASSWORD: ss_mongo_pass_2024
  MONGO_DB: sanosysalvos
  MONGO_URL: mongodb://mongoroot:ss_mongo_pass_2024@mongodb:27017/sanosysalvos?authSource=admin

  # MinIO
  MINIO_ROOT_USER: minioadmin
  MINIO_ROOT_PASSWORD: ss_minio_pass_2024
  MINIO_BUCKET_FOTOS: fotos-mascotas

  # Google OAuth2 — reemplazar con credenciales reales de Google Cloud Console
  GOOGLE_CLIENT_ID: "TU_GOOGLE_CLIENT_ID.apps.googleusercontent.com"
  GOOGLE_CLIENT_SECRET: "TU_GOOGLE_CLIENT_SECRET"

  # JWT
  JWT_SECRET: "QGwOsHZ3K7WQYoHntlCKpfy7Rt4uLEOruf1WZI/hGWl90qmOHWdWz0iLtVFxTnVS"
  JWT_EXPIRATION_MS: "86400000"

  # Grafana
  GRAFANA_ADMIN_USER: admin
  GRAFANA_ADMIN_PASSWORD: admin1234
